defaultScope(4);
intRange(-8, 7);

c1_Phone = Abstract("c1_Phone");
c2_networking = c1_Phone.addChild("c2_networking").withCard(1, 1);
c3_wifi = c2_networking.addChild("c3_wifi").withCard(0, 1);
c4_typeB = c3_wifi.addChild("c4_typeB").withCard(0, 1);
c5_typeG = c3_wifi.addChild("c5_typeG").withCard(0, 1);
c6_typeN = c3_wifi.addChild("c6_typeN").withCard(0, 1);
c7_bluetooth = c2_networking.addChild("c7_bluetooth").withCard(0, 1);
c8_mobile = c2_networking.addChild("c8_mobile").withCard(0, 1);
c9_nfc = c2_networking.addChild("c9_nfc").withCard(0, 1);
c10_location = c1_Phone.addChild("c10_location").withCard(0, 1).withGroupCard(1, 1);
c11_gps = c10_location.addChild("c11_gps").withCard(0, 1);
c12_agps = c10_location.addChild("c12_agps").withCard(0, 1);
c13_gpu = c1_Phone.addChild("c13_gpu");
c14_PhoneWithGps = Clafer("c14_PhoneWithGps").withCard(1, 1).extending(c1_Phone);
c17_PhoneWithWifi = Clafer("c17_PhoneWithWifi").withCard(1, 1).extending(c1_Phone);
c24_PhonewithWifiAndGpsNoBluetoothOrNfc = Clafer("c24_PhonewithWifiAndGpsNoBluetoothOrNfc").withCard(1, 1).extending(c1_Phone);
c37_PhoneWithGpu = Clafer("c37_PhoneWithGpu").withCard(1, 1).extending(c1_Phone);
Constraint(all([decl([p = local("p")], global(c1_Phone))], some(join(join(p, c2_networking), c8_mobile))));
c14_PhoneWithGps.addConstraint(some(join(join($this(), c10_location), c11_gps)));
c17_PhoneWithWifi.addConstraint(some(join(join(join($this(), c2_networking), c3_wifi), c6_typeN)));
c24_PhonewithWifiAndGpsNoBluetoothOrNfc.addConstraint(and(and(some(join(join($this(), c2_networking), c3_wifi)), some(join(join($this(), c10_location), c11_gps))), not(or(some(join(join($this(), c2_networking), c7_bluetooth)), some(join(join($this(), c2_networking), c9_nfc))))));
c37_PhoneWithGpu.addConstraint(some(join($this(), c13_gpu)));
