defaultScope(1);
intRange(-8, 7);

c1_Person = Abstract("c1_Person");
c2_age = c1_Person.addChild("c2_age").withCard(1, 1);
c3_maritalStatus = c1_Person.addChild("c3_maritalStatus").withCard(1, 1).withGroupCard(1, 1);
c4_neverMarried = c3_maritalStatus.addChild("c4_neverMarried").withCard(0, 1);
c5_married = c3_maritalStatus.addChild("c5_married").withCard(0, 1);
c6_spouse = c5_married.addChild("c6_spouse").withCard(1, 1);
c28_divorced = c3_maritalStatus.addChild("c28_divorced").withCard(0, 1);
c38_childs = c1_Person.addChild("c38_childs");
c63_parents = c1_Person.addChild("c63_parents").withCard(0, 2);
c78_Alice = Clafer("c78_Alice").withCard(1, 1).extending(c1_Person);
c84_Bob = Clafer("c84_Bob").withCard(1, 1).extending(c1_Person);
c88_Carol = Clafer("c88_Carol").withCard(1, 1).extending(c1_Person);
c2_age.refTo(Int);
c6_spouse.refToUnique(c1_Person);
c38_childs.refToUnique(c1_Person);
c63_parents.refToUnique(c1_Person);
c3_maritalStatus.addConstraint(implies(or(some(join($this(), c5_married)), some(join($this(), c28_divorced))), greaterThanEqual(joinRef(join(joinParent($this()), c2_age)), constant(3))));
c6_spouse.addConstraint(notEqual(joinRef($this()), joinParent(joinParent(joinParent($this())))));
c6_spouse.addConstraint(equal(joinRef(join(join(join(joinRef($this()), c3_maritalStatus), c5_married), c6_spouse)), joinParent(joinParent(joinParent($this())))));
c38_childs.addConstraint($in(joinParent($this()), joinRef(join(joinRef($this()), c63_parents))));
c38_childs.addConstraint($in(joinRef(join(join(join(joinParent($this()), c3_maritalStatus), c5_married), c6_spouse)), joinRef(join(joinRef($this()), c63_parents))));
c38_childs.addConstraint(lessThan(joinRef(join(joinRef($this()), c2_age)), joinRef(join(joinParent($this()), c2_age))));
c63_parents.addConstraint($in(joinParent($this()), joinRef(join(joinRef($this()), c38_childs))));
c78_Alice.addConstraint(equal(joinRef(join($this(), c2_age)), constant(4)));
c78_Alice.addConstraint(some(join(join($this(), c3_maritalStatus), c5_married)));
c84_Bob.addConstraint(equal(joinRef(join($this(), c2_age)), constant(5)));
c88_Carol.addConstraint(equal(joinRef(join($this(), c2_age)), constant(1)));
