defaultScope(1);
intRange(-8, 7);

c1_options = Abstract("c1_options");
c16_comp = Abstract("c16_comp");
c23_ECU = Abstract("c23_ECU").extending(c16_comp);
c24_display = Abstract("c24_display").extending(c16_comp);
c43_plaECU = Abstract("c43_plaECU").extending(c23_ECU);
c2_size = c1_options.addChild("c2_size").withCard(1, 1).withGroupCard(1, 1);
c3_small = c2_size.addChild("c3_small").withCard(0, 1);
c4_large = c2_size.addChild("c4_large").withCard(0, 1);
c5_cache = c1_options.addChild("c5_cache").withCard(0, 1);
c6_size = c5_cache.addChild("c6_size").withCard(1, 1);
c7_fixed = c6_size.addChild("c7_fixed").withCard(0, 1);
c17_version = c16_comp.addChild("c17_version").withCard(1, 1);
c25_server = c24_display.addChild("c25_server").withCard(1, 1);
c35_options = c24_display.addChild("c35_options").withCard(1, 1).extending(c1_options);
c44_display = c43_plaECU.addChild("c44_display").withCard(1, 2).extending(c24_display);
c53_ECU1 = Clafer("c53_ECU1").withCard(1, 1).extending(c43_plaECU);
c54_ECU2 = Clafer("c54_ECU2").withCard(0, 1).extending(c43_plaECU);
c55_master = c54_ECU2.addChild("c55_master").withCard(1, 1);
c65_telematicsSystem = Clafer("c65_telematicsSystem").withCard(1, 1);
c66_channel = c65_telematicsSystem.addChild("c66_channel").withCard(1, 1).withGroupCard(1, 1);
c67_single = c66_channel.addChild("c67_single").withCard(0, 1);
c68_dual = c66_channel.addChild("c68_dual").withCard(0, 1);
c69_extraDisplay = c65_telematicsSystem.addChild("c69_extraDisplay").withCard(0, 1);
c70_size = c65_telematicsSystem.addChild("c70_size").withCard(1, 1).withGroupCard(1, 1);
c71_small = c70_size.addChild("c71_small").withCard(0, 1);
c72_large = c70_size.addChild("c72_large").withCard(0, 1);
c6_size.refTo(Int);
c17_version.refTo(Int);
c25_server.refToUnique(c23_ECU);
c55_master.refToUnique(c53_ECU1);
Constraint(and(and(some(join(join(global(c65_telematicsSystem), c66_channel), c68_dual)), some(join(global(c65_telematicsSystem), c69_extraDisplay))), some(join(join(global(c65_telematicsSystem), c70_size), c72_large))));
c1_options.addConstraint(implies(and(some(join(join($this(), c2_size), c3_small)), some(join($this(), c5_cache))), some(join(join(join($this(), c5_cache), c6_size), c7_fixed))));
c16_comp.addConstraint(equal(joinRef(join($this(), c17_version)), add(constant(1), constant(2))));
c24_display.addConstraint(greaterThanEqual(joinRef(join($this(), c17_version)), joinRef(join(joinRef(join($this(), c25_server)), c17_version))));
c44_display.addConstraint(and(equal(joinRef(join($this(), c25_server)), joinParent($this())), none(join(join($this(), c35_options), c5_cache))));
c65_telematicsSystem.addConstraint(and(and(and(and(ifOnlyIf(some(join(join($this(), c66_channel), c68_dual)), some(global(c54_ECU2))), ifOnlyIf(some(join($this(), c69_extraDisplay)), equal(card(join(global(c53_ECU1), c44_display)), constant(2)))), ifOnlyIf(some(join($this(), c69_extraDisplay)), implies(some(global(c54_ECU2)), equal(card(join(global(c54_ECU2), c44_display)), constant(2))))), ifOnlyIf(some(join(join($this(), c70_size), c72_large)), none(join(join(join(join(global(c43_plaECU), c44_display), c35_options), c2_size), c3_small)))), ifOnlyIf(some(join(join($this(), c70_size), c71_small)), none(join(join(join(join(global(c43_plaECU), c44_display), c35_options), c2_size), c4_large)))));
